version: '3'
services:
  next-demo:
    image: next-demo:latest
    container_name: next-demo
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
